name: custom_in_place_searchable_dropdown
description: A custom searchable dropdown widget for Flutter, 
  in which the search bar appears on the dropdown itself.
version: 1.0.0+1
homepage: https://github.com/your_username/custom_dropdown
repository: https://github.com/your_username/custom_dropdown.git

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: custom_dropdown
        pluginClass: CustomDropdownPlugin
        ios:
          pluginClass: CustomDropdownPlugin
